module.exports.cssLoader  = function (config){
  config.module
  .rule("css")
  .test(/\.css$/)
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader");

const types = ["vue-modules", "vue", "normal-modules", "normal"];
// types.forEach((item) => {
config.module
  .rule("scss")
  .test(/\.scss|sass$/)
  .oneOf("vue-modules")
  .resourceQuery(/module/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("scssloader")
  .loader("sass-loader")
  .end()
  .end()
  .oneOf("normal")
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("scssloader")
  .loader("sass-loader")
  .end()
  .end()
  .oneOf("vue")
  .resourceQuery(/\?vue/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("scssloader")
  .loader("sass-loader")
  .end()
  .end()
  .oneOf("normal-modules")
  .test(/\.module\.\w+$/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("scssloader")
  .loader("sass-loader")
  .end()
  .end();
}



