module.exports.cssLoader  = function (config){
  config.module
  .rule("css")
  .test(/\.css$/)
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader");

const types = ["vue-modules", "vue", "normal-modules", "normal"];
// types.forEach((item) => {
config.module
  .rule("less")
  .test(/\.less$/)
  .oneOf("vue-modules")
  .resourceQuery(/module/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("lessloader")
  .loader("less-loader")
  .end()
  .end()
  .oneOf("normal")
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("lessloader")
  .loader("less-loader")
  .end()
  .end()
  .oneOf("vue")
  .resourceQuery(/\?vue/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("lessloader")
  .loader("less-loader")
  .end()
  .end()
  .oneOf("normal-modules")
  .test(/\.module\.\w+$/)
  .use("vue-style")
  .loader("vue-style-loader")
  .end()
  .use("style")
  .loader("style-loader")
  .end()
  .use("cssloader")
  .loader("css-loader")

  .end()
  .use("postcss-loader")
  .loader("postcss-loader")
  .end()
  .use("lessloader")
  .loader("less-loader")
  .end()
  .end();
}


// });

// config.module
//   .rule("less")
//   .test(/\.less$/)
//   .use("vue-style-loader")
//     .loader("vue-style-loader")
//     .end()
//   .use("style")
//   .loader("style-loader")
//   .end()
//   .use("cssloader")
//   .loader("css-loader")
//   .end()
//   .use("lessloader")
//   .loader("less-loader");
